from __future__ import annotations

import csv
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .paper_pack import require_release_gate


ROOT = Path(__file__).resolve().parents[1]
NUMBERS = ROOT / "paper" / "numbers.json"
SWEEP = ROOT / "reports" / "benchmark" / "sweep.csv"
PHASE7 = ROOT / "reports" / "phase7_status.md"
NOTES = ROOT / "reports" / "benchmark" / "notes.md"
OUT = ROOT / "paper" / "example_report.md"


def _load_numbers() -> dict[str, dict[str, Any]]:
    return json.loads(NUMBERS.read_text(encoding="utf-8"))


def _load_sweep() -> list[dict[str, str]]:
    with SWEEP.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def _value(numbers: dict[str, dict[str, Any]], key: str) -> Any:
    return numbers[key]["value"]


def _source(numbers: dict[str, dict[str, Any]], key: str) -> str:
    record = numbers[key]
    line = record.get("source_line")
    suffix = "" if line in (None, "") else f":{line}"
    return f"{record['source']}{suffix}"


def _fmt(value: Any, digits: int = 3) -> str:
    if isinstance(value, float):
        return f"{value:.{digits}f}".rstrip("0").rstrip(".")
    return str(value)


def _table(headers: list[str], rows: list[list[Any]]) -> list[str]:
    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(str(cell) for cell in row) + " |")
    return lines


def _section_from_file(title: str, path: Path) -> list[str]:
    if not path.exists():
        return [f"## {title}", "", f"`{path.relative_to(ROOT).as_posix()}` is missing.", ""]
    return [
        f"## {title}",
        "",
        f"Source: `{path.relative_to(ROOT).as_posix()}`",
        "",
        *path.read_text(encoding="utf-8", errors="replace").splitlines()[2:],
        "",
    ]


def main() -> int:
    try:
        require_release_gate()
    except RuntimeError as exc:
        print(str(exc))
        return 1
    numbers = _load_numbers()
    sweep_rows = _load_sweep()
    default = next(row for row in sweep_rows if row["config"] == "ours_mxfp4_b32_pk16_pv8")
    generated = datetime.now(timezone.utc).isoformat()
    git_sha = str(_value(numbers, "ours_mxfp4_b32_latency_us") and numbers["ours_mxfp4_b32_latency_us"]["git_sha"])

    lines: list[str] = [
        "# Example Report: Native MXFP4 Persistent-State GDN Accelerator",
        "",
        "> AUTO-GENERATED by `scripts/example_report.py`. Do not hand-edit paper numbers here.",
        "",
        f"- Generated: `{generated}`",
        f"- Data SHA: `{git_sha}`",
        f"- Canonical numbers: `{NUMBERS.relative_to(ROOT).as_posix()}`",
        f"- Provenance map: `paper/provenance.json`",
        f"- Phase 7 pack: `paper/pack/submission_{git_sha}.zip`",
        "",
        "## Executive Summary",
        "",
        (
            "This example report summarizes the current simulation-only MXFP4 accelerator evidence "
            "for one Gated DeltaNet decode layer. The default configuration is "
            "`MXFP4 B=32, P_K=16, P_V=8` with persistent resident state and packed output."
        ),
        "",
        *(
            _table(
                ["Metric", "Current Value", "Source"],
                [
                    ["Default latency", f"{_fmt(_value(numbers, 'ours_mxfp4_b32_latency_us'))} us/token", _source(numbers, "ours_mxfp4_b32_latency_us")],
                    ["RTL cosim tokens", _value(numbers, "ours_mxfp4_b32_tokens_cosim"), _source(numbers, "ours_mxfp4_b32_tokens_cosim")],
                    ["Speedup vs H100", f"{_fmt(_value(numbers, 'headline_speedup_vs_h100'))}x", _source(numbers, "headline_speedup_vs_h100")],
                    ["Speedup vs USC FPGA", f"{_fmt(_value(numbers, 'headline_speedup_vs_usc'))}x", _source(numbers, "headline_speedup_vs_usc")],
                    ["Energy efficiency vs H100", f"{_fmt(_value(numbers, 'headline_energy_efficiency_vs_h100'))}x", _source(numbers, "headline_energy_efficiency_vs_h100")],
                    ["Power", f"{_fmt(_value(numbers, 'ours_mxfp4_b32_power_w'))} W", _source(numbers, "ours_mxfp4_b32_power_w")],
                    ["Qwen realistic capture", _value(numbers, "qwen_capture_status"), _source(numbers, "qwen_capture_status")],
                ],
            )
        ),
        "",
        "## Main Results",
        "",
        *(
            _table(
                ["Configuration", "Latency", "Power", "LUT", "DSP", "BRAM", "Notes"],
                [
                    [
                        "NVIDIA H100 PCIe BF16",
                        f"{_fmt(_value(numbers, 'h100_baseline_latency_us'))} us",
                        f"{_fmt(_value(numbers, 'h100_baseline_power_w'))} W TDP",
                        "--",
                        "--",
                        "--",
                        "External USC-cited baseline",
                    ],
                    [
                        "USC BF16 FPGA",
                        f"{_fmt(_value(numbers, 'usc_baseline_latency_us'))} us",
                        f"<={_fmt(_value(numbers, 'usc_baseline_power_w'))} W",
                        "--",
                        "--",
                        "--",
                        "External USC-cited baseline",
                    ],
                    [
                        "Ours MXFP4 B=32 P_K=16 P_V=8",
                        f"{_fmt(_value(numbers, 'ours_mxfp4_b32_latency_us'))} us",
                        f"{_fmt(_value(numbers, 'ours_mxfp4_b32_power_w'))} W",
                        f"{_fmt(_value(numbers, 'ours_mxfp4_b32_lut_pct'))}%",
                        f"{_fmt(_value(numbers, 'ours_mxfp4_b32_dsp_pct'))}%",
                        f"{_fmt(_value(numbers, 'ours_mxfp4_b32_bram_pct'))}%",
                        "Fresh RTL cosim + Vivado impl",
                    ],
                ],
            )
        ),
        "",
        "## Phase 6 Sweep Table",
        "",
        *(
            _table(
                ["Config", "Block", "P_K", "P_V", "Tokens", "Latency us", "Power W", "Energy mJ", "LUT %", "BRAM %", "DSP %", "Evidence"],
                [
                    [
                        row["config"],
                        row["block_size"],
                        row["p_k"],
                        row["p_v"],
                        row["tokens"],
                        row["latency_us"],
                        row["power_w"],
                        row["energy_mj"],
                        row["lut_pct"],
                        row["bram_pct"],
                        row["dsp_pct"],
                        f"{row['latency_source_kind']} / {row['impl_status']}",
                    ]
                    for row in sweep_rows
                ],
            )
        ),
        "",
        "## Verification And Implementation",
        "",
        *(
            _table(
                ["Check", "Result", "Source"],
                [
                    ["HLS C-sim vectors", f"{_value(numbers, 'hls_csim_vectors_passed')}/{_value(numbers, 'hls_csim_vectors_total')}", _source(numbers, "hls_csim_vectors_passed")],
                    ["HLS C-sim freshness", _value(numbers, "hls_csim_freshness_status"), _source(numbers, "hls_csim_freshness_status")],
                    ["HLS csynth Fmax", f"{_fmt(_value(numbers, 'ours_mxfp4_b32_csynth_fmax_mhz'))} MHz", _source(numbers, "ours_mxfp4_b32_csynth_fmax_mhz")],
                    ["HLS csynth latency", f"{_value(numbers, 'ours_mxfp4_b32_csynth_latency_cycles')} cycles", _source(numbers, "ours_mxfp4_b32_csynth_latency_cycles")],
                    ["RTL cosim latency", f"{_value(numbers, 'ours_mxfp4_b32_latency_cycles')} cycles", _source(numbers, "ours_mxfp4_b32_latency_cycles")],
                    ["Vivado synth WNS", f"{_fmt(_value(numbers, 'ours_mxfp4_b32_synth_wns_ns'))} ns", _source(numbers, "ours_mxfp4_b32_synth_wns_ns")],
                    ["Vivado impl WNS", f"{_fmt(_value(numbers, 'ours_mxfp4_b32_impl_wns_ns'))} ns", _source(numbers, "ours_mxfp4_b32_impl_wns_ns")],
                ],
            )
        ),
        "",
        "## Quantization Accuracy Snapshot",
        "",
        *(
            _table(
                ["Metric", "Value", "Source"],
                [
                    ["MXFP4 B=32 output cosine", _fmt(_value(numbers, "synthetic_mxfp4_b32_output_cosine"), 6), _source(numbers, "synthetic_mxfp4_b32_output_cosine")],
                    ["MXFP4 B=32 output rel L2", _fmt(_value(numbers, "synthetic_mxfp4_b32_output_rel_l2"), 6), _source(numbers, "synthetic_mxfp4_b32_output_rel_l2")],
                    ["MXFP4 B=32 state rel L2", _fmt(_value(numbers, "synthetic_mxfp4_b32_state_rel_l2"), 6), _source(numbers, "synthetic_mxfp4_b32_state_rel_l2")],
                    ["MXFP4 B=16 output cosine", _fmt(_value(numbers, "synthetic_mxfp4_b16_output_cosine"), 6), _source(numbers, "synthetic_mxfp4_b16_output_cosine")],
                    ["MXFP4 B=16 output rel L2", _fmt(_value(numbers, "synthetic_mxfp4_b16_output_rel_l2"), 6), _source(numbers, "synthetic_mxfp4_b16_output_rel_l2")],
                    ["INT4 fallback output cosine", _fmt(_value(numbers, "synthetic_int4_output_cosine"), 6), _source(numbers, "synthetic_int4_output_cosine")],
                ],
            )
        ),
        "",
        "## Tensor Ablation",
        "",
        *(
            _table(
                ["Tensor Dropped To MXFP4", "Synthetic Output Cosine", "Source"],
                [
                    ["q", _fmt(_value(numbers, "ablation_q_output_cosine"), 6), _source(numbers, "ablation_q_output_cosine")],
                    ["k", _fmt(_value(numbers, "ablation_k_output_cosine"), 6), _source(numbers, "ablation_k_output_cosine")],
                    ["v", _fmt(_value(numbers, "ablation_v_output_cosine"), 6), _source(numbers, "ablation_v_output_cosine")],
                    ["gate", _fmt(_value(numbers, "ablation_gate_output_cosine"), 6), _source(numbers, "ablation_gate_output_cosine")],
                    ["state", _fmt(_value(numbers, "ablation_state_output_cosine"), 6), _source(numbers, "ablation_state_output_cosine")],
                ],
            )
        ),
        "",
        "## Long-Run State And Stress Evidence",
        "",
        *(
            _table(
                ["Metric", "MXFP4 state", "MXFP8 state", "Source"],
                [
                    [
                        "1024-token final output cosine",
                        _fmt(_value(numbers, "synthetic_drift_mxfp4_final_output_cosine"), 6),
                        _fmt(_value(numbers, "synthetic_drift_mxfp8_final_output_cosine"), 6),
                        _source(numbers, "synthetic_drift_mxfp4_final_output_cosine"),
                    ],
                    [
                        "1024-token final state rel L2",
                        _fmt(_value(numbers, "synthetic_drift_mxfp4_final_state_rel_l2"), 6),
                        _fmt(_value(numbers, "synthetic_drift_mxfp8_final_state_rel_l2"), 6),
                        _source(numbers, "synthetic_drift_mxfp4_final_state_rel_l2"),
                    ],
                    [
                        "Combined-stress worst output cosine",
                        _fmt(_value(numbers, "synthetic_stress_combined_stress_state_mxfp4_b16_worst_output_cosine"), 6),
                        _fmt(_value(numbers, "synthetic_stress_combined_stress_state_mxfp8_b16_worst_output_cosine"), 6),
                        _source(numbers, "synthetic_stress_combined_stress_state_mxfp4_b16_worst_output_cosine"),
                    ],
                ],
            )
        ),
        "",
        "## Storage And Traffic Evidence",
        "",
        *(
            _table(
                ["Metric", "Value", "Source"],
                [
                    ["MXFP4 B=32 state bytes", _value(numbers, "state_storage_mxfp4_b32_bytes"), _source(numbers, "state_storage_mxfp4_b32_bytes")],
                    ["Reduction vs FP32", f"{_fmt(_value(numbers, 'state_storage_mxfp4_b32_reduction_vs_fp32_pct'))}%", _source(numbers, "state_storage_mxfp4_b32_reduction_vs_fp32_pct")],
                    ["Reduction vs BF16", f"{_fmt(_value(numbers, 'state_storage_mxfp4_b32_reduction_vs_bf16_pct'))}%", _source(numbers, "state_storage_mxfp4_b32_reduction_vs_bf16_pct")],
                    ["Naive off-chip state traffic", f"{_value(numbers, 'offchip_mxfp4_b32_naive_three_pass_bytes_per_token')} bytes/token", _source(numbers, "offchip_mxfp4_b32_naive_three_pass_bytes_per_token")],
                    ["Persistent off-chip state traffic", f"{_value(numbers, 'offchip_mxfp4_b32_persistent_bytes_per_token')} bytes/token", _source(numbers, "offchip_mxfp4_b32_persistent_bytes_per_token")],
                ],
            )
        ),
        "",
        "## Generated Paper Assets",
        "",
        *(
            _table(
                ["Asset", "Path"],
                [
                    ["Main results table", "`paper/tables/main_results.tex`"],
                    ["Quantization ablation table", "`paper/tables/ablation_quantization.tex`"],
                    ["Block-size ablation table", "`paper/tables/ablation_block_size.tex`"],
                    ["Area breakdown table", "`paper/tables/area_breakdown.tex`"],
                    ["Recurrent-state stress table", "`paper/tables/recurrent_state_stress.tex`"],
                    ["State storage/traffic table", "`paper/tables/state_storage_traffic.tex`"],
                    ["Result macros", "`paper/snippets/result_macros.tex`"],
                    ["Parallelism Pareto figure", "`paper/figures/parallelism_pareto.pdf`"],
                    ["Block-size accuracy figure", "`paper/figures/block_size_accuracy.pdf`"],
                    ["Latency comparison figure", "`paper/figures/latency_comparison.pdf`"],
                    ["Area breakdown figure", "`paper/figures/area_breakdown.pdf`"],
                    ["Roofline figure", "`paper/figures/roofline.pdf`"],
                    ["State precision stress figure", "`paper/figures/state_precision_stress.pdf`"],
                    ["State traffic figure", "`paper/figures/state_traffic.pdf`"],
                ],
            )
        ),
        "",
        "## Caveats",
        "",
        f"- Realistic Qwen PPL/accuracy is not available yet; current status is `{_value(numbers, 'qwen_capture_status')}`.",
        "- Current accuracy tables are synthetic-only and should be described that way.",
        "- Non-default sweep rows are included as Phase 6 evidence; use the default row for the current headline numbers.",
        "",
        *_section_from_file("Phase 7 Status", PHASE7),
        *_section_from_file("Benchmark Notes", NOTES),
    ]

    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(OUT.relative_to(ROOT).as_posix())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
